AllCops:
  TargetRubyVersion: 2.7.1

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/migrate/**/**'

Style/Documentation:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'config/**/**'
    - 'bin/**'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/**/**'
    - 'bin/**'

Bundler/OrderedGems:
  Enabled: false
